### ISSUE TITLE
Count CC on 5 functions

### ISSUE THREAD

**Issue by pandaseal** [adambenali/java-algorithms-implementation#2]
Do this by hand or as comments in the function.

**Comment by pandaseal** [comment]
SegmentTree.java line 1074: query(). CC = 28
for: 1, if: 16, &&: 9, ||:1; ? : : -, case: - , catch: -, while: -

**Comment by pandaseal** [comment]
BinaryHeap.java line 722: heapDown(). CC = 42
for: -, if: 15, &&: 21, ||: 5; ? : : -, case: - , catch: -, while: -
These are summed and 1 added.

**Comment by pandaseal** [comment]
BinaryHeap.java line 186: heapDown(). CC = 41
for: -, if: 8, &&: 25, ||: 5; ? : : 2, case: - , catch: -, while: -
These are summed and 1 added.

**Comment by ChangGabriel** [comment]
SplayTree.java line 67: splay(). CC = 28
for: -, if: 19, &&: 6, ||:1 ; ? : : 1 , case: - , catch: -, while: -

**Comment by ChangGabriel** [comment]
SkipList.java line 115: getPredecessor(). CC = 11
for: 0 if: 6, &&: 1, ||:1; ? : : -, case: - , catch: -, while: 3

**Comment by jrutqvist** [comment]
Nice job! 💯
