### ISSUE TITLE
Manually instrument 10 functions with high CC

### ISSUE THREAD

**Issue by adambenali** [adambenali/java-algorithms-implementation#3]
The function should have a CC > 10 and have bad test coverage.
Write 2 tests each, preferably for 2 different functions (among these 10!).

**Comment by jrutqvist** [comment]
I'm gonna call dibs on the function index 0 (instrumentation point indexes 0-99) for Matrix.add to test instrumentation on!

**Comment by ChangGabriel** [comment]
I will do one test for Matrix.compare() line:27 - 57  and Dijkstra::getShortestPath line:57 - 134.

**Comment by adambenali** [comment]
I'm taking `FenwickTree::combined` (index 100->199) and `FenwickTree::separate` (index 200->299).

**Comment by jrutqvist** [comment]
Ill do BinarySearchTree:getDFS with indexes 300-399!

**Comment by hanzhsun** [comment]
I will take BinaryHeapArray::validateNode (index 400->499) and BinaryHeapTree::validateNode (index 500->599).

**Comment by jrutqvist** [comment]
Ok @hanzhsun @ChangGabriel I'll do instrumentation for your functions now! As well as for two functions for @pandaseal

**Comment by jrutqvist** [comment]
Ill call indexes 6 (600-699) and 7 (700-799) for @ChangGabriel's functions and 8 and 9 for @pandaseal's functions

**Comment by jrutqvist** [comment]
@pandaseal gets KdTree.searchNode and SuffixTree:TreePrinter:getString!

**Comment by pandaseal** [comment]
I will write tests for `Matrix.equals()` and `Primes.isPrime()`.
